spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amir-learn-db
    username: postgres
    password: amir1124
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
